#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

ynh_app_setting_set_default --key=php_upload_max_filesize --value=5G
ynh_app_setting_set_default --key=php_post_max_size --value=5G
# backup database 
cp -pr "$install_dir/dist/inc/digiquiz.db" "/tmp/digiquiz.db.bak" 2>/dev/null || true

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="dist/inc/digiquiz.db dist/fichiers"


#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."
ynh_config_add --template=".env.production" --destination="$install_dir/.env.production"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building $app..."

pushd "$install_dir"
	ynh_hide_warnings ynh_exec_as_app npm install
	ynh_hide_warnings ynh_exec_as_app npm run build
popd

rm -rf "$install_dir/dist/fichiers"
ln -s "$data_dir/fichiers" "$install_dir/dist/fichiers"

# restore database
cp -pr "/tmp/digiquiz.db.bak" "$install_dir/dist/inc/digiquiz.db" 2>/dev/null || true
chown -R $app:www-data "$install_dir"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
